name: Exec Rspec
on: [push]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        ruby_version:
          - 3.0
          - 3.1
          - 3.2
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '${{ matrix.ruby_version }}'
          bundler: latest
          bundler-cache: true
      - name: Run sample
        run: bundle exec ruby example/sample.rb
      - name: Run RSpec
        run: RUBYOPT='-W:deprecated' bundle exec rspec spec